### ISSUE TITLE
View All Posts (3)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-rest-samurai-planets#36]
As a reader, I would like to see a list of all the Posts so that I can choose a post that seems interesting to read.

**Given** the user is in the Rare application  
**When** they select the `Posts` menu option  
**Then** they should be directed to the Posts list page  
**And** each post in the list should display the title, author and category  
**And** the list should ONLY contain approved Posts  
**And** the list should ONLY contain Posts with a publication date that is in the past  
**And** the list should be in order of publication date with the most recent on top

**Comment by Russ716** [comment]
- post list on client side looks at http://localhost:8088/posts to fetch the posts. 
- it currently displays extraneous information "date" and "tags" - remove these. 
- It displays the information in a table, can delete (or comment out for now) the entire lines containing date/tags

**Comment by ameena-mashaikh** [comment]
**SERVER SIDE**
 
- Create a list function in the PostView class from the file posts_views.py
- List function should include a GET request
- Use .all() to retrieve all of the objects __.objects.all( )
- Serialize the request for listing all of the posts, make sure _many=True_ because we are access multiple objects
- Return the response with the serialized data
