### ISSUE TITLE
View All Categories (3)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-rest-samurai-planets#37]
As an admin I would like to see all the available categories so that I can choose to edit or delete one, or see that I should add a new one.

**Given** an admin is in the app  
**When** they select the `Category Management` link in the menu  
**Then** they should be directed to a page that lists all the Category names ordered alphabetically  

> **NOTE:** For the time being it is acceptable to treat all users as `admin` users. There is a future story about enforcing user permissions.

**Comment by mandapandaa8** [comment]
-post list on client side looks at http://localhost:8088/categories to fetch the categories.
-ensure category manager on client, and the server agree with this address,
-it currently displays extraneous information "date" and "tags" - remove these.
-It displays the information in a table, can delete (or comment out for now) the entire lines containing date/tags

**Comment by mandapandaa8** [comment]
-Create a list function in the CategoryView class from the file categories_views.py
-List function should include a GET request
-Use .all() to retrieve all of the objects __.objects.all( )
-Serialize the request for listing all of the categories, make sure many=True because we are access multiple objects
-Return the response with the serialized data
